pandoc: Autospec creation for update from version 2.11.4 to version 2.12
Albert Krewinkel (29):
      Lua: always load built-in Lua scripts from default data-dir
      JATS writer: escape special chars in reference elements.
      JATS templates: tag author.name as string-name
      CslJson writer: fix compiler warning
      Lua: add module "pandoc.path"
      Improve docs for directory, normalize
      Use hslua-module-path 0.1.0
      Fix stack config
      Check that all documented functions are present.
      Add tests for search_path_separator
      doc/lua-filters.md: fix, improve docs for `pandoc.mediabag.fetch`
      doc/lua-filters.md: improve docs for `pandoc.mediabag.insert`
      Lua filters: use same function names in Haskell and Lua
      CI: use cabal 2.2 when building with GHC 8.0.2. (#7085)
      pandoc.cabal: use common stanza to reduce duplication (#7086)
      Avoid unnecessary use of NoImplicitPrelude pragma (#7089)
      Jira: require jira-wiki-markup 1.3.3
      T.P.Shared: export `handleTaskListItem`. [API change]
      Org: support task_lists extension
      Allow tasty 1.4.*
      T.P.Error: remove unused variables
      JATS writer: replace attribute "pub-type" with "publication-format".
      JATS writer: add date-type to pub-date elements
      Org reader: fix bug in org-ref citation parsing.
      tests: print accurate location if a test fails
      Lua: use strict evaluation when retrieving AST value from the stack
      Jira writer: use Span identifiers as anchors
      Jira writer: use noformat instead of code for unknown languages.
      Fix, amend changelog.

Andrew Dunning (1):
      LaTeX template: Update to iftex package (#7073)

Dmitrii Kovanikov (1):
      Allow base64-bytestring-1.2.*

John MacFarlane (167):
      Update AUTHORS.md.
      Clean up BibTeX parsing.
      Improve docs for cite-method.
      Markdown writer: handle math right before digit.
      Use latest citeproc.
      Use tasty-bench instead of criterion for benchmarks.
      CslJson writer:  output `[]` if no references in input,
      Require citeproc 0.3.0.6.
      RST reader: fix handling of header in CSV tables.
      Add shell.nix.
      Makefile: give allocation data in benchmarks.
      BibTeX writer fixes.  Closes #7067.
      BibTeX writer: use doclayout and doctemplate.
      Add default.bibtex to repository.
      Remove superfluous import
      shell.nix - install zlib
      cabal.project - more heap space
      Add parseOptionsFromArgs [API change, addition].
      Test suite:  a more robust way of testing the executable.
      Fixed some compiler warnings in tests.
      CI: use haskell/actions/setup.
      stack.yaml - use commonmark-0.1.1.4 for GHC 9
      Markdown reader: improved handling of mmd link attributes in references.
      ODT reader: give more information if zip can't be unpacked.
      ODT reader: finer-grained errors on parse failure.
      Use lts-17.2 resolver (with ghc 8.10.3).
      Add new unexported module T.P.XMLParser.
      Correctly parse "raw" date value in markdown references metadata.
      T.P.Class: Add getTimestamp [API change].
      Use getTimestamp instead of getCurrentTime in writers.
      Add MANUAL section on reproducible builds.
      Add command test for #7092
      Fix command test 5686
      LaTeX reader improvements.
      Avoid an unnecessary withRaw.
      Clean up benchmark code.
      Remove Ext_fenced_code_attributes from allowed commonmark attributes.
      LaTeX reader: remove unnecessary line
      T.P.Error: export `renderError`.
      HTML reader: fix bad handling of empty src attribute in iframe.
      Rename Text.Pandoc.XMLParser -> Text.Pandoc.XML.Light...
      Split up T.P.XML.Light into submodules.
      Add orig copyright/license info for code derived from xml-light.
      Add T.P.XML.Light.Cursor.
      Revert "Add T.P.XML.Light.Cursor."
      Docx reader: use Map instead of list for Namespaces.
      T.P.Shared: cleanup.
      LaTeX writer: adjust hypertargets to beginnings of paragraphs.
      LaTeX template: disable `` ?` `` and `` !` `` ligatures.
      Revert "LaTeX template: disable `` ?` `` and `` !` `` ligatures."
      T.P.PDF: disable `smart` when building PDF via LaTeX.
      T.P.XML Improve fromEntities.
      DocBook, JATS, OPML readers: performance optimization.
      'make bench': Create csv files for comparison.
      Clarify `tex_math_dollars` extension.
      make bench: compare against a baseline, use datestamps for bench results.
      MANUAL: block-level formatting is not allowed in line blocks.
      HTML reader: efficiency improvements.
      Benchmark improvements.
      T.P.Readers.LaTeX.Parsing: improve braced'.
      LaTeX reader:  avoid macro resolution code if no macros defined.
      LaTeX reader: Another small improvement to macro handling.
      HTML reader: small efficiency improvements.
      T.P.Shared: remove some obsolete functions [API change].
      HTML reader: small performance tweak.
      LaTeX reader: further performance optimization.
      LaTeX reader: removed sExpanded in state.
      LaTeX reader: further optimizations in satisfyTok.
      Fix changelog-helper.sh
      Update changelog.
      Text.Pandoc.UTF8: change IO functions to return Text, not String.
      Text.Pandoc.MIME: add exported function getCharset.
      T.P.Error: Add PandocUnsupportedCharsetError constructor...
      When downloading content from URL arguments, be sensitive to...
      Fall back to latin1 if UTF-8 decoding fails...
      T.P.CSV: fix parsing of unquoted values.
      Add linux benchmark to CI.
      Rename benchmark in CI.
      benchmark CI improvements.
      Remove weigh-pandoc.
      Use latest skylighting.
      CI: Add 'benchmark' to benchmark cache key.
      Update tests for changes to https URLs.
      CI: hide successes in linux test output.
      Add tools/parseTimings.pl.
      Use skylighting 0.10.4.
      Add xml-conduit to stack.yaml extra-deps.
      Split off T.P.Readers.LaTeX.Accent.
      Factor out T.P.Readers.LaTeX.Table.
      Factor out T.P.Readers.LaTeX.Citation.
      trypandoc: add 2 second timeout.
      LaTeX reader: remove two unnecessary parsers in inline.
      Move setDefaultLanguage to T.P.Readers.LaTeX.Lang.
      LaTeX reader efficiency improvements.
      LaTeX reader: another small efficiency improvement.
      Markdown reader efficiency improvements.
      Fix bug in last commit.
      CI: don't use --test-option with older cabal versions (< 3).
      Fix CI for older cabal versions.
      Factor out T.P.Readers.LaTeX.Math.
      LaTeX writer: use function instead of map for accent lookup.
      T.P.Readers.LaTeX: Don't export tokenize, untokenize.
      Remove superfluous imports.
      Change T.P.Readers.LaTeX.SIunitx to export a command map...
      Removed unnecessary pragmas.
      Factor out T.P.Readers.LaTeX.Macro.
      Make T.P.Readers.LaTeX.Types an unexported module.
      Use -split-sections in creating release binary.
      Avoid split-sections for Windows rc.
      cabal.project: don't explicitly set -trypandoc.
      trypandoc: remove unneeded imports.
      MacOS release build: remove -split-sections.
      Update changelog.
      stack.yaml - use citeproc 0.3.0.8
      Add doc/libraries.md.
      Split up T.P.Writers.Markdown...
      Split out T.P.Writers.LaTeX.Lang.
      Split out T.P.Writers.LaTeX.Citation.
      Split out T.P.Writers.LaTeX.Util.
      Split out T.P.Readers.LaTeX.Inline.
      Moved more into T.P.Readers.LaTeX.Lang.
      Move enquote commands to T.P.LaTeX.Lang.
      Remove T.P.Readers.LaTeX.Accent.
      Add T.P.Readers.LaTeX.Include.
      Revert "Add T.P.Readers.LaTeX.Include."
      Update changelog
      Update AUTHORS.md.
      Update date on manual.
      Bump version to 2.12
      Update man page.
      Update README.md.
      Update stack resolver.
      Relax `--abbreviations` rules so that a period isn't required.
      Revert "Relax `--abbreviations` rules so that a period isn't required."
      Revert "Revert "Relax `--abbreviations` rules so that a period isn't required.
      Shared: Change defaultUserDataDirs -> defaultUserDataDir.
      Logging: Add EnvironmentVariableUndefined constructor to LogMessage.
      Add fields for CSL optinos to Opt.
      Implement environment variable interpolation in defaults files.
      Allow `${.}` in defaults files paths...
      Makefile: debpkg: use new multi-arch GHC 8.10.4 docker...
      Makefile: exit smoothly if no prior benchmark files found.
      Makefile: choose linux docker image depending on arch.
      More Makefile tweaks around docker linux build.
      Fix docker image.
      Allow `--resource-path` to accumulate.
      Don't --rm docker.
      Fix linux nightly build to use ghc 8.10.3.
      linux build script: handle architecture for aarch64.
      Makefile: Remove ARCH
      linux build script: set architecture to 'unknown' when no match.
      make debpkg: send docker output to docker.log in the host.
      Avoid subprocess for docker run.
      Set --user in docker run to avoid permission issues.
      Add script to build an ARM binary on AWS.
      LaTeX reader: support hyperref command.
      build-arm.sh: retrieve build artifacts after success.
      LaTeX reader: handle table cells containing `&` in `\verb`.
      Fixed build-arm script.
      build-arm.sh: print total build time
      build-arm.sh: env variable for ARTIFACTS.
      Update changelog.
      More changelog fixes.
      Update date in changelog and manual.
      Update RELEASE-CHECKLIST
      build-arm.sh: fix elapsed time.
      Use correct architecture in .tar.gz for linux.

Lorenzo (1):
      Update default ODT style

Loïc Grobol (1):
      Wrap url colours in braces in the default LaTeX template (#7121)

Mauro Bieg (1):
      LaTeX writer: change BCP47 lang tag from jp to ja

Nick Berendsen (1):
      ePub writer: `belongs-to-collection` metadata (#7063)

Nils Carlson (1):
      DocBook reader: Support informalfigure (#7079)

Nixon Enraght-Moony (1):
      Document no template fallback for absolute path (#7088)

Salim B (1):
      Fix/update URLs and use HTTP**S** where possible (#7122)

maurerle (1):
      revealjs writer: add 'center' option for vertical slide centering.