pandoc: Autospec creation for update from version 2.14.2 to version 2.16.2
Albert Krewinkel (56):
      Switch to hslua-2.0
      Lua: marshal Pandoc values as userdata
      Lua: marshal Attr values as userdata
      Lua: marshal Inline elements as userdata
      Lua: marshal Version values as userdata
      changelog.md: update some Lua-related entries
      Lua: convert IOErrors to PandocErrors in pandoc.pipe function
      Lua: marshal Citation values as userdata objects
      Lua: marshal Block values as userdata objects
      Lua: marshal ListAttributes values as userdata objects
      Lua: generate constants in module pandoc programmatically
      Lua: marshal SimpleTable values as userdata objects
      Lua: fix `pandoc.utils.stringify` regression
      Lua: re-add `t` and `tag` property to Attr values
      Add a short guide to pandoc's sources
      Update description of T.P.PDF
      Lua: increase strictness when getting attribute keys
      Lua: fix placement of tests for Block elements in pandoc module tests
      Lua: use hslua module abstraction where possible
      Lua: re-add `content` property to Link elements
      Lua: restore List behavior of MetaList
      Lua: load module `pandoc.path` on startup
      Lua: restore `content` property on Header elements
      Lua tests: ensure Block elements have expected properties
      Lua: allow to compare, show Citation values
      Lua: allow omitting the 2nd parameter in pandoc.Code constructor
      Lua: display Attr values using their native Haskell representation
      Lua: be more forgiving when retrieving the Image `caption` property
      Lua: re-add `content` property to Strikeout elements
      Lua tests: ensure Inline elements have all expected properties
      Lua: fix typo in SoftBreak constructor
      Lua: add missing space in "package not found" message
      Require latest hslua (2.0.1).
      Lua: include lpeg module (#7649)
      Lua: always load lpeg as global module
      Lua: display Pandoc values using their native Haskell representation
      T.P.Error: sort errors in handleError by exit code
      MANUAL.txt: update table of exit codes and corresponding errors
      doc/lua-filters.md: add section on global modules, including lpeg
      Lua: allow to pass custom reader options to `pandoc.read`
      Lua: add Pushable instance for ReaderOptions
      Lua: ensure that 're' module is always available.
      stack.yaml: require latest lpeg
      Lua: fix argument order in constructor `pandoc.Cite`.
      JATS template: fix equal-contrib attribute
      JATS template: fix incomplete previous commit
      Lua: load `re` module available into global of the same name
      JATS writer: add URL to element citation entries
      JATS writer: ensure figures are wrapped with `<p>` in list items.
      LaTeX reader: add rudimentary support for `\autoref` (#7693)
      Lua: make loading of global LPeg modules more robust
      Lua: set `lpeg`, `re` as globals; allow shared lib access via require
      Lua: fix global module loading (#7701)
      Capture `alt-text` in JATS figures (#7703)
      Rename doc/custom-reader.lua to doc/custom-readers.md
      Minor changelog edits.

Aner Lucero (1):
      Use simpleFigure in Readers.

Christian Despres (1):
      Writers.Shared: Improve toLegacyTable.

Christophe Dervieux (2):
      mention revealjs support of title-toc in MANUAL
      Add disableLayout variable in revealjs template

Emily Bourke (17):
      pptx: Make first heading title if slide level is 0
      pptx: Restructure tests
      pptx: Add support for more layouts
      pptx: Fix capitalisation of notesMasterId
      pptx: Don’t add relationships unnecessarily
      pptx: Include all themes in output archive
      pptx: Fix presentation rel numbering
      pptx: Copy embedded fonts from reference doc
      pptx: Fix logic for choosing Comparison layout
      pptx: Add support for incremental lists
      pptx: Support specifying slide background images
      pptx: Support footers in the reference doc
      pptx-footers: Replace fixed dates with yaml date
      pptx: Remove excessive layout tests
      pptx: Fix list level numbering
      pptx: Remove outdated comment
      pptx: Line up continuation paragraphs

Ezwal (1):
      Docx reader: Add placeholder for word diagram

Fabián Heredia Montiel (1):
      Update build files (#7696)

Francesco Mazzoli (1):
      Support `--reference-location` for HTML output (#7461)

Jeroen de Haas (1):
      Do not leak working directory in TikZ filter

John MacFarlane (196):
      App: Move output-file writing out of PandocMonad action.
      MANUAL: document error code 25
      PandocIO: derive MonadCatch, MonadThrow, MonadMask.
      Clean up PDF module.
      Markdown reader: fix interaction of --strip-comments and list
      Fix test for #7521.
      Lua subsystem and custom writers: generalize types from PandocIO...
      PDF: generalize type of makePDF...
      Text.Pandoc.Filter:  Generalize type of applyFilters...
      T.P.App.OutputSettings: Generalize some types...
      Class: Generalize type of extractMedia.
      Text.Pandoc.Class: add readStdinStrict method to PandocMonad.
      Reorganize App to make it easier to limit IO in main loop.
      Comment out unused module.
      Ensure we have unique ids for wp:docPr and pic:cNvPr elements.
      T.P.Image: svgToPng, change first parameter from WriterOptions to Int.
      Add haddock for dpi parameter.
      Image: Generalize svgToPng to MonadIO.
      Docx writer: handle SVG images.
      Remove unneeded import.
      Add `--sandbox` option.
      Add more potential threats to security section of manual.
      Improve asciidoc escaping for `--` in URLs.  Closes #7529.
      Hlint: ignore "Use void."
      RTF reader: Ignore `\pgdsc` group.
      RTF reader:  if doc begins with {\rtf1 ... } only parse its contents.
      Extensions: put Ext_short_subsuperscripts in alphabetical order.
      Minor renaming to avoid shadowing.
      RTF reader: better handling of `\*` and bookmarks.
      Makefile: disable ansi tricks for tasty; use v2- instead of new-.
      CI:  disable ansi-tricks in tasty.
      Logging: add NotUTF8Encoded constructor to LogMessage.
      App: Issue NotUTF8Encoded warning when falling back to latin1.
      RTF reader: support `\binN` for binary image data.
      Use dev version of citeproc.
      MANUAL: Document formats affected by `--reference-location`.
      Org reader: don't parse a list as first item in a list item.
      Remove redundant import.
      Fix command test for #7557.
      Use latest dev citeproc.
      Add note to Security section that commonmark is better...
      Docx writer: make id used in native_numbering predictable.
      Modernize quick-cabal Makefile target
      Use latest dev version of texmath.
      RST reader: handle escaped colons in reference definitions.
      Fix quick-cabal target
      HTML writer: set "hash" to True by default (for reveal.js).
      stack.yaml: use lts-18.10 resolver.
      Fix code blocks using `--preserve-tabs`.
      Use --system-ghc in make quick.
      Update list of supported source languages in org writer.
      Org writer: don't indent contents of code blocks.
      Fix linter warning.
      Use skylighting-0.12, skylighting-core-0.12.
      Alphabetize Extension constructors.
      Markdown writer: use `underline` class rather than `ul` for underline.
      Fix changelog date for 2.14.2.
      Use babel, not polyglossia, with xelatex.
      Ignore (and gobble parameters of) CSLReferences environment.
      LaTeX reader: Recognize that `\vadjust` sometimes takes "pre".
      Stop doing lint in CI.
      Command tests: raise error if command doesn't begin with `%`.
      Add missing `%` on command tests.
      Use pretty-simple to format native output.
      Remove unused epub test file features.epub.
      Make test/epub/wasteland.epub valid.
      Revert "Remove unused epub test file features.epub."
      test/epub: an excerpt from The Wasteland is enough!
      Use latest citeproc.
      HTML writer: pass through inline math environments with KaTeX.
      HTML writer: pass through `\ref` and `\eqref`...
      HTML writer: render `\ref` and `\eqref` as inline math...
      HTML reader: handle empty tbody element in table.
      BibTeX parser: fix expansion of special strings in series...
      Update documentation for definition_list extension.
      RST writer: properly handle anchors to ids...
      Better implementation of splitStrWhen
      Switch from pretty-simple to pretty-show for native output.
      Further test updates for switch to pretty-show.
      EPUB writer: treat epub:type "frontispiece" as front matter.
      Add `footnotes` to default `gfm` etxensions.
      Depend on pandoc-types 1.23, remove Null constructor on Block.
      Fix compareXML helper in Tests.Writers.OOXML.
      Update cabal.project
      Update tests for babel-related changes in latex template.
      Powerpoint writer: consolidate text run nodes.
      Revert "Powerpoint writer: consolidate text run nodes."
      OOXML tests: use pretty-printed form to display diffs.
      Powerpoint writer: consolidate text runs when possible.
      Avoid bad wraps in markdown writer at the Doc Text level.
      Improve quick-cabal target
      Allow time 1.12.
      Don't prepend `file://` to `--syntax-definition` on Windows.
      Translations: don't depend on the fact that Aeson Object is...
      Makefile; fix quick-cabal executable path report
      LaTeX reader: Properly handle `\^` followed by group closing.
      Use latest emojis.
      Stack: use latest doclayout
      LaTeX reader: Implement siunitx v3 commands.
      Update wasteland tests.
      Fix warning
      Remove splitSentences from T.P.Shared [API change].
      T.P.Writers.Shared: Export splitSentences as a Doc Text transform.
      T.P.Writers.Shared: remove 'breakable'...
      Require doclayout >= 0.3.1.1.
      Depend on latest dev version of commonmark.
      Allow aeson 2.0
      cabal.project: Dependencies to build with aeson 2.
      Revert "Depend on pandoc-types 1.23, remove Null constructor on Block."
      cabal build: go back to using aeson < 2 for now.
      Fix markdown parsing bug for math in bracketed spans and links.
      CI: add workflow to test pdf production...
      CI: fix yaml workflow.
      CI: pdf test: need an input file!
      CI: more tweaks to pdf tests.
      CI: remove linux-pdf for now.
      Ensure that babel is loaded also with pdflatex.
      FormatHeuristics: remove `.tei.xml` extension for TEI.
      Markdown reader: don't parse links or bracketed spans as citations.
      Fix line numbers in source code with reveal.js
      SelfContained: fix bug that caused everything to be made a data uri.
      Move splitStrWhen to T.P.Citeproc.Util.
      Provisional changelog updates.
      Use pandoc-types 1.22.1.
      Use texmath 0.12.3.2
      Use citeproc 0.6, commonmark 0.2.2.1, commonmark-extensions 0.2.2
      Update changelog.
      Org reader: allow an initial :PROPERTIES: drawer to add to metadata.
      Update changelog.
      Bump to 2.15, updaet man page.
      Minor reformatting in chargelog.
      Use ipynb 0.1.0.2.
      Update changelog.
      CircleCI: use homebrew not curl to install stack.
      Fix 2.15 release date on changelog.
      Update AUTHORS.md
      Fix description of sandbox feature in changelog.
      Fix conformance errors in test/epub/features.epub and
      Fixed test/epub/img.epub and img_no_cover.epub...
      Clean up wasteland.epub and formatting.epub from reader tests.
      Fix more epub files in epub reader tests.
      Fix a copy/paste bug in Lua marshalling code.
      Switch back from HsYAML to yaml.
      Change JSON encodings of some types.
      Markdown writer: Be sure to quote special values in YAML metadata.
      short-guide: Transitions -> Transformations.
      Require latest skylighting (0.12.1).
      Fix trypandoc so it builds with aeson > 2.
      Allow time 1.13
      Bump to 2.16, update changelog.
      Regenerate man page.
      Update changelog.
      Makefile: remove man/pandoc.1 dependency for debpkg.
      Makefile: use --nonmoving-gc RTS option when running benchmarks.
      Docx writer: use getTimestamp for modification times in reference.docx.
      Docx reader:  don't let first line indents trigger block quotes.
      Bump to 2.16.1, update changelog.
      Allow tasty-bench 0.3.x.
      Allow latest tasty-bench, update changelog.
      Markdown reader: Improve inlinesInBalancedBrackets.
      Allow `plain` to be used in raw attribute syntax.
      CI: remove test on ghc 8.0.2.
      Add interface for custom readers written in Lua. (#7671)
      Fuller sample custom reader.
      Pass ReaderOptions to custom readers as second parameter.
      Replace old sample custom reader with a full-featured reader for creole.
      LaTeX reader: add 'uri' class when parsing `\url`.
      Remove some extra stuff from data/creole.lua.
      Properly handle commented lines in BibTeX/BibLaTeX.
      With `-t latex-smart`, don't generate `\ldots` from ellipsis.
      Accept empty `--metadata-file`.
      Require Cabal 2.4.  Use wildcards...
      cabal.project: Require transformers >= 0.5.6.
      Require ghc >= 8.6, base >= 4.12.
      Fix parsing of `%` in bibtex fields.
      Remove unneeded package dependencies from benchmark target.
      Fix misspelled extension name in manual.
      Markdown writer: don't create autolinks when this loses information.
      Use latest dev texmath.
      Babel mappings: use ancientgreek for grc.
      Add doc for custom-readers.
      MediaWiki writer: use HTML spans for anchors when header has id.
      HTML writer: Don't create invalid `data-` attribute...
      MediaWiki writer: fix code for generating spans for header IDs.
      Remove unused line.
      Lua tests:  reset path and cpath when testing 'require' fallback.
      Use released texmath.
      Update changelog.
      Minor changelog edits.
      More changelog edits
      Bump to 2.16.2
      Update man page.
      Add custom-writers.md.
      Update AUTHORS.md
      yamlBsToRefs: allow multiple YAML documents.
      Update changelog.

Joseph C. Sible (1):
      Fix build on GHC 9.2

Kolen Cheung (6):
      Ipynb reader handleData: support text/markdown (#7561)
      fix!: rst mime type
      feat(ipynb reader): add more Jupyter's "Raw NBConvert Format"
      feat(ipynb reader): get cell output mime from raw_mimetype too
      feat(ipynb writer): add more Jupyter's "Raw NBConvert Format"
      fix!(ipynb writer): improve round trip identity

Milan Bracke (4):
      Avoid blockquote when parent style has more indent
      Docx reader: fix handling of nested fields
      Docx parser: implement PAGEREF fields
      Docx reader: fix handling of empty fields

Quinn (3):
      Add missing type for Image title
      Improve order of Image fields
      Rephrase pandoc.path docs (#7548)

Rowan Rodrik van der Molen (2):
      Support for <indexterm>s when reading DocBook (#7607)
      Add `<titleabbr>` support to DocBook reader

S.P.H (1):
      Update bash_completion.tpl

Salim B (2):
      Harmonize spelling of 'slide show'
      Add some more info regarding `--slide-level=0`

Samuel Tardieu (3):
      Remove redundant $
      DocBook reader: honor linenumbering attribute
      asciidoc writer: translate numberLines attribute to linesnum switch

Simon Schuster (1):
      LaTeX-parser: restrict \endinput to current file

Tristan Stenner (3):
      Docx writer: move ": " out of the caption bookmark.
      Update test golden master for docx native numbering
      Docx writer: add IDs to native_numbering test

William Lupton (1):
      Clarify 'attributes' extension support

hseg (1):
      Make babel use more idiomatic

nuew (1):
      epub: Add EPUB3 subject metadata (authority/term)

willj-dev (1):
      RST reader: handle class attribute for for custom roles (#7700)