pandoc: Autospec creation for update from version 2.14.0.3 to version 2.14.1
Aner Lucero (2):
      Remove duplicated alt text in HTML output.
      HTML5 writer, remove aria-hidden when explicit atl text is provided.

Jan Tojnar (1):
      DocBook reader: add support for citerefentry (#7437)

John MacFarlane (36):
      Use dev version of doctemplates.
      reveal.js writer: Go back to setting boolean values for variables.
      ImageSize: Add Tiff constructor for ImageType.
      Markdown writer: put space between Plain and following fenced Div.
      Require commonmark-pandoc >= 0.2.2.1.
      Set proper initial source name in parsing BibTeX.
      Text.Pandoc.Error: fix line calculations in reporting parsec errors.
      Allow `$` characters in bibtex keys.
      Improve punctuation moving with `--citeproc`.
      Use dev version of citeproc.
      Use dev version of citeproc.
      Docx writer: support figure numbers.
      Docx writer: Fixed a couple bugs in Figure numbering.
      Docx writer: Add table numbering for captioned tables.
      CircleCI: change to using xcode 11.1.0 (macOS 10.14.4).
      Upgrade Debian 10 AMI for build-arm.sh.
      Add doc/faqs.md.
      Revert "LaTeX template: move title, author, date up to top of preamble."
      Add FAQ on converting from/to PDF
      Revamp note citation handling.
      Citeproc: cleanup and efficiency improvement in deNote.
      Add command test for #7394.
      HTML reader: add col, colgroup to 'closes' definitions
      Markdown reader:  don't try to read contents in self-closing HTML tag.
      T.P.PDF, convertImage: normalize paths.
      RST reader: fix regression with code includes.
      Always use / when adding directory to image path with extractMedia.
      Improved parsing of raw LaTeX from Text streams (rawLaTeXParser).
      PDF: Fix svgIn path error.
      LaTeX reader: Support `\cline` in LaTeX tables.
      DocBook reader: handle images with imageobjectco elements.
      LaTeX reader: avoid trailing hyphen in translating languages.
      Use skylighting 0.11.
      Use doctemplates 0.4.1 and citeproc 0.10.
      Fix comment syntax in cabal.project
      Bump to 2.14.1, update changelog and man page.

Mauro Bieg (1):
      document-css: reset overflow-wrap on code blocks

Michael Hoffmann (2):
      Recognize data-external when reading HTML img tags (#7429)
      Don't incorporate externally linked images in EPUB documents (#7430)